### ISSUE TITLE
flight number for a given date

### ISSUE THREAD

**Issue by RafaGuzmanNYU** [supercoderz/pyflightdata#22]
Hi
I need to search by flight number for a given date. Is there any way to apply such fliter using the API? Thanks

**Comment by hari-allamraju** [comment]
I have pushed a first draft. There is a get_flight_for_date method now that takes the flight number and a date in the YYYYMMDD format. Do you want to take the code from master branch and give it a try? It might be a bit a it does the filtering *after* it gets all the data that you can get with your level of access

**Comment by RafaGuzmanNYU** [comment]
Dear Hari

Thanks a lot for your help and for building the function. However, as you
mentioned, this is just a post-filter while what I would need is to make
the filter while launching the query, to retrieve only the information from
a flight number in a given date. Is that something you can do?

By the way, I don't really get how to use the "page" and "limit" arguments
in the "get_history_by_flight_number" function. I think the limit argument
allows you to reduce the number of results but doesn´t allow you to raise
the limit to let´s say 100 results. The page argument I just dont know how
to use it.
I have an antenna and contribute to the flightradar24 community with my
feed and therefore I have a Business subscription that should allow me to
get access to the whole database.

Thanks again Hari

Regards

Rafael

**Comment by hari-allamraju** [comment]
It is not possible to filter at the point of starting a query because none of the FR24 URL's allow this. Bear in mind this API is an un-official API which just scrapes the pages as a web scraper doe, maybe a bit more refined way. So we cannot have anything that isn't already done on the web site. AFAIK there is no flight number for a date feature on the web page.

Limit is a vague feature. There is a limit parameter on the URL's and I have seen this work only to limit data to under a 100 results and never to get more data.

Page works because for users who can get more data, you can pass page numbers from 1 to n until you stop getting results. There was an issue with this but it was fixed by another user and is included in the latest version on pypi - 0.7

I will release this date search with the post filter into 0.8 later this week

**Comment by RafaGuzmanNYU** [comment]
Thank you so much for your help, Hari

I guess I will have to wait until FR24 release the official API to go
deeper into it..

By the way, as i am not a Python expert, once you release the 0.8 version,
shall I just run the "pip install pyflightdata" command in the prompt to
get the package updated?

Thank you so much

Best Regards

Rafa

**Comment by hari-allamraju** [comment]
Yes just do a pip install to update the package

**Comment by hari-allamraju** [comment]
New version 0.8 is released
