### ISSUE TITLE
When pulling historical data I receive HTTP error 402 

### ISSUE THREAD

**Issue by thejoe01** [supercoderz/pyflightdata#26]
Thank you for your library! I'm really enjoying on using it. My goal is to retrieve in the shortest time possible the historical data about one particular airport. The problem is when I loop on  `f.get_history_by_flight_number(f_id)` it is continuing to show me HTML error 402 make me wait for 10 seconds for retrying and it seems to be repeated in a casual manner. Can you help understand why? 

P.S. I have the business plan

**Comment by hari-allamraju** [comment]
The library is just a wrapper over Fr24 pages and is not an official API. So it happens from time to time that when Fr24 decides to throttle the rate of accessing a page, it will throw a 404 error. 402 error is the first time though. A sleep interval of 30 seconds on 1 min bet ween calls is good.

However I dont recommend hitting it too often because this is an un-official API and we may all get blocked from using it.
