### ISSUE TITLE
how to get access to history data

### ISSUE THREAD

**Issue by DavidSamir907** [supercoderz/pyflightdata#27]
Hello! Thank you very much for this library, I would like to know if it is possible to access the history of the airport and limit it by dates, and if it is possible to access the history of flight paths by aircraft (latitude, longitude and elevation).

**Comment by hari-allamraju** [comment]
Hi - this is not possible. You will have to first download the full history and then filter on the client side. The library is just a wrapper over HTTP calls made by the FR24 pages, so it cannot implement any complex logic.

Search by flightpath is not possible because there is no such data on FR24 pages.
